### ISSUE TITLE
Indonesian language. How to have english version

### ISSUE THREAD

**Issue by sharik709** [bliblidotcom/vue-rangedate-picker#73]
Looks like plugin by default uses indonesian langauge. How can I have it in english version. and also how can I change placeholder from "-" to "Date Range"?

But thank you so much for awesome plugin. It saved some of my time.

**Comment by sharik709** [comment]
Ohh, got it. it would be  ```i18n="EN"```
Thank you.

**Comment by curiousPup** [comment]
Please explain how did you put that. It doesn't work for me.

**Comment by curiousPup** [comment]
thank you!
